---
micronaut:
    application:
        name: issue492
                
#Uncomment to set server port
#    server:
#        port: 8080

---
consul:
  client:
    registration:
      fail-fast: false
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
